-- =====================================================================
-- PulsePass - V1: esquema base
-- ---------------------------------------------------------------------
-- Cubre las entidades obligatorias de la seccion 7 del PRD:
--   venues, events, artists, event_artists, users, user_profiles, tickets
-- y las reglas de integridad de la seccion 8.
--
-- Esta migracion NO debe modificarse una vez aplicada (pregunta 4 del PRD):
-- Flyway guarda un checksum en flyway_schema_history y cualquier cambio
-- posterior rompe la validacion en los entornos donde ya se ejecuto.
-- =====================================================================


-- ---------------------------------------------------------------------
-- venues                                            FR-VEN-001 .. 003
-- ---------------------------------------------------------------------
CREATE TABLE venues (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    code     VARCHAR(50)  NOT NULL,
    name     VARCHAR(150) NOT NULL,
    city     VARCHAR(100) NOT NULL,
    address  VARCHAR(200) NOT NULL,
    capacity INTEGER      NOT NULL,
    active   BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_venues            PRIMARY KEY (id),
    CONSTRAINT uk_venues_code       UNIQUE (code),
    -- FR-VEN-003 / BR: la capacidad debe ser mayor que cero.
    CONSTRAINT ck_venues_capacity   CHECK (capacity > 0)
);


-- ---------------------------------------------------------------------
-- events                                            FR-EVT-001 .. 005
-- ---------------------------------------------------------------------
-- BR-001: todo evento pertenece a exactamente un venue  -> venue_id NOT NULL
-- BR-002: un venue alberga cero o muchos eventos        -> la FK vive aqui
-- BR-008: los enums se almacenan por nombre estable     -> VARCHAR + CHECK
-- ---------------------------------------------------------------------
CREATE TABLE events (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    event_code  VARCHAR(50)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    description TEXT,
    category    VARCHAR(30)  NOT NULL,
    status      VARCHAR(30)  NOT NULL,
    event_date  TIMESTAMP    NOT NULL,
    minimum_age INTEGER      NOT NULL DEFAULT 0,
    venue_id    BIGINT       NOT NULL,

    CONSTRAINT pk_events             PRIMARY KEY (id),
    CONSTRAINT uk_events_event_code  UNIQUE (event_code),
    CONSTRAINT fk_events_venue       FOREIGN KEY (venue_id) REFERENCES venues (id),

    -- FR-EVT-004: la categoria pertenece al catalogo definido.
    CONSTRAINT ck_events_category CHECK (category IN (
        'MUSIC', 'SPORTS', 'TECHNOLOGY', 'EDUCATION', 'CULTURE', 'ENTERTAINMENT'
    )),
    -- FR-EVT-003: el estado pertenece al catalogo definido.
    CONSTRAINT ck_events_status CHECK (status IN (
        'DRAFT', 'PUBLISHED', 'SOLD_OUT', 'CANCELLED', 'FINISHED'
    )),
    CONSTRAINT ck_events_minimum_age CHECK (minimum_age >= 0)
);


-- ---------------------------------------------------------------------
-- artists                                           FR-ART-001 .. 002
-- ---------------------------------------------------------------------
CREATE TABLE artists (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    stage_name VARCHAR(120) NOT NULL,
    country    VARCHAR(80),
    genre      VARCHAR(80),
    active     BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_artists            PRIMARY KEY (id),
    CONSTRAINT uk_artists_stage_name UNIQUE (stage_name)
);


-- ---------------------------------------------------------------------
-- event_artists  (tabla asociativa N:M)             FR-ART-003 / BR-003
-- ---------------------------------------------------------------------
-- La PK compuesta impide repetir el mismo par evento-artista (AC-003).
-- Sin ella, nada evitaria insertar dos veces (CMF-2026, Solar Beat).
-- ---------------------------------------------------------------------
CREATE TABLE event_artists (
    event_id  BIGINT NOT NULL,
    artist_id BIGINT NOT NULL,

    CONSTRAINT pk_event_artists        PRIMARY KEY (event_id, artist_id),
    CONSTRAINT fk_event_artists_event  FOREIGN KEY (event_id)  REFERENCES events (id),
    CONSTRAINT fk_event_artists_artist FOREIGN KEY (artist_id) REFERENCES artists (id)
);


-- ---------------------------------------------------------------------
-- users                                             FR-USR-001 .. 002
-- ---------------------------------------------------------------------
-- R-004: User representa identidad de dominio, no credenciales.
-- "user" es palabra reservada en PostgreSQL, por eso la tabla es "users".
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(60)  NOT NULL,
    email    VARCHAR(150) NOT NULL,
    active   BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_users          PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email    UNIQUE (email)
);


-- ---------------------------------------------------------------------
-- user_profiles                                     FR-USR-003 .. 004
-- ---------------------------------------------------------------------
-- BR-004 / AC-004: un usuario tiene como maximo un perfil.
-- La FK sola daria 1:N; es el UNIQUE(user_id) el que convierte la
-- relacion en un verdadero 1:1 dentro de PostgreSQL.
-- ---------------------------------------------------------------------
CREATE TABLE user_profiles (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT      NOT NULL,
    first_name VARCHAR(80) NOT NULL,
    last_name  VARCHAR(80) NOT NULL,
    phone      VARCHAR(30),
    city       VARCHAR(100),
    birth_date DATE,

    CONSTRAINT pk_user_profiles      PRIMARY KEY (id),
    CONSTRAINT uk_user_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users (id)
);


-- ---------------------------------------------------------------------
-- tickets                                           FR-TKT-001 .. 005
-- ---------------------------------------------------------------------
-- BR-005: un ticket pertenece a exactamente un user y un event.
-- BR-006: Ticket es entidad, no un @ManyToMany simple, porque tiene
--         atributos propios (ticket_code, type, price, status, purchase_date).
-- BR-007 / NFR-008: el precio usa NUMERIC, nunca float/double.
-- ---------------------------------------------------------------------
CREATE TABLE tickets (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    ticket_code   VARCHAR(50)   NOT NULL,
    type          VARCHAR(30)   NOT NULL,
    price         NUMERIC(12,2) NOT NULL,
    status        VARCHAR(30)   NOT NULL,
    purchase_date TIMESTAMP     NOT NULL,
    user_id       BIGINT        NOT NULL,
    event_id      BIGINT        NOT NULL,

    CONSTRAINT pk_tickets             PRIMARY KEY (id),
    CONSTRAINT uk_tickets_ticket_code UNIQUE (ticket_code),
    CONSTRAINT fk_tickets_user        FOREIGN KEY (user_id)  REFERENCES users (id),
    CONSTRAINT fk_tickets_event       FOREIGN KEY (event_id) REFERENCES events (id),

    -- FR-TKT-003: el precio no puede ser negativo.
    CONSTRAINT ck_tickets_price CHECK (price >= 0),
    -- FR-TKT-004
    CONSTRAINT ck_tickets_type CHECK (type IN (
        'GENERAL', 'VIP', 'BACKSTAGE', 'STUDENT'
    )),
    -- FR-TKT-005
    CONSTRAINT ck_tickets_status CHECK (status IN (
        'RESERVED', 'PAID', 'CANCELLED', 'USED'
    ))
);


-- ---------------------------------------------------------------------
-- Indices
-- ---------------------------------------------------------------------
-- Las PK y los UNIQUE ya crean su propio indice automaticamente en
-- PostgreSQL, por eso aqui solo se indexan las FK y las columnas que
-- aparecen en los filtros y ordenamientos frecuentes del PRD.
-- ---------------------------------------------------------------------
CREATE INDEX idx_events_venue_id       ON events (venue_id);
CREATE INDEX idx_events_status         ON events (status);
CREATE INDEX idx_events_event_date     ON events (event_date);
CREATE INDEX idx_events_category       ON events (category);

CREATE INDEX idx_event_artists_artist  ON event_artists (artist_id);

CREATE INDEX idx_tickets_user_id       ON tickets (user_id);
CREATE INDEX idx_tickets_event_id      ON tickets (event_id);
CREATE INDEX idx_tickets_status        ON tickets (status);
CREATE INDEX idx_tickets_purchase_date ON tickets (purchase_date);
